### ISSUE TITLE
Erro: Failed to load dynamic library 

### ISSUE THREAD

**Issue by lucascardo12** [chrisnorman7/worldsmith#5]
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'C:\Users\lucas.cardoso.SIMPLESIP\Documents\repositorios\flutter_application_3\SDL2.dll': error code 126
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      new Sdl
package:dart_sdl/src/sdl.dart:90
#3      main
package:flutter_application_3/main.dart:7
#4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:130:25)
#5      _rootRun (dart:async/zone.dart:1426:13)
#6      _CustomZone.run (dart:async/zone.dart:1328:19)
#7      _runZoned (dart:async/zone.dart:1861:10)
#8      runZonedGuarded (dart:async/zone.dart:1849:12)
#9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:126:5)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

**Comment by chrisnorman7** [comment]
Hi,
I’m not at the computer at the minute to read this properly, but it looks
as though you haven’t copied the relevant DLLs into your project directory.

If you are using Worldsmith Studio, you can use the DLLs from there.

HTH.

**Comment by lucascardo12** [comment]
could you give me the link of that Worldsmith Studio?

**Comment by chrisnorman7** [comment]
Sure. It can be found [here](https://github.com/chrisnorman7/worldsmith_studio).

**Comment by lucascardo12** [comment]
ok vlw
